name: Auto Build for Vita

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [ run_build ]

env:
  BUILD_TYPE: Release
  VITASDK: /usr/local/vitasdk

jobs:
  VitaBuild:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3

      - name: Install VitaSDK
        run: |
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          ./bootstrap-vitasdk.sh
          ./install-all.sh
      
      - name: First build step
        continue-on-error: true
        run: |
          cd
          git clone https://github.com/Hammerill/Sand-Box2D && cd Sand-Box2D
          mkdir build
          cd build
          cmake .. -DBUILD_WINDOWS=OFF -DBUILD_VITA=ON
        
      - name: Second build step
        run: |
          cmake ..
          make -j4
      
      - name: Output VPK
        uses: actions/upload-artifact@v3
        with:
          name: VPK
          path: |
            *.vpk
