name: Auto Build for Vita

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [ run_build ]

env:
  VITASDK: /usr/local/vitasdk

jobs:
  Vita:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3

      - name: Install VitaSDK
        run: |
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          ./bootstrap-vitasdk.sh
          ./install-all.sh
      
      - name: Build project
        run: |
          git clone https://github.com/Hammerill/Sand-Box2D && cd Sand-Box2D
          mkdir build
          cd build
          cmake .. -DBUILD_WINDOWS=OFF -DBUILD_VITA=ON
          make -j4
      
      - name: Output VPK
        uses: actions/upload-artifact@v3
        with:
          name: Sand-Box2D.vpk
          path: |
            Sand-Box2D/build/*.vpk
